@startuml ShipObject

object "<u>ship1 : Ship</u>" as ship1 {
  shipName = "Titanic"
  yearBuilt = "March 31st, 1909"
}

object "<u>ship2 : CruiseShip</u>" as ship2 {
  shipName = "MVGemini"
  yearBuilt = "May 30th, 1991"
  maxNumberPassengers = 100
}

object "<u>ship3 : CargoShip</u>" as ship3 {
  shipName = "EverGiven"
  yearBuilt = "September 25th, 2018"
  cargoCapacityInTonnage = 220940
}

@enduml
